### ISSUE TITLE
Add a filter in the research for boss dps and not only overall dps when loading spec comps.

### ISSUE THREAD

**Issue by Laniox** [gitarrg/lorgs#32]
I haven't wrote the exact code for it, but that would be greatly appreciated if there was a filter available on the website to be able to filter the top 50 "bossdps" in comparison to the top 50 "dps" (overall).

That would help the user that wants to play his class as a single target dps to understand how cd are used, when the majority of people on his class plays aoe builds. (Works even for the ones with 10% aoe builders that are being the top 50, so the 90% other people can't see how it goes in single target rotation)

The changes that may be needed would be in load spec ranking, change "dps" to "bossdps" with an option that interact with the UI of website.

Thanks a lot if you find the time to do so !

**Comment by vincentullmann** [comment]
Hey there,

there is an option already here:
https://i.imgur.com/IhGjVLI.png

Does that help?

**Comment by Laniox** [comment]
Hey!
It totally helps yeah ! That makes me feel dumb haha
I was imagining a "sort by" category, close of the kill time filter, and haven't seen it in the timeline part
I believe it would at least help to add a line about that in the "help" section of the website as I haven't seen it written here :)

Thanks for the help on that
