### ISSUE TITLE
Compare own logs to top ones

### ISSUE THREAD

**Issue by Seraf** [gitarrg/lorgs#6]
Hello !

First, thanks for this apps, I found it very useful as it provides really good visibility about "major trends".

I was thinking that could be nice to: Bring our own warcraftlogs URL, and according to the boss+class we are tracking, display the players in the raid and how they placed their cooldown.

I don't figure yet if it could be nice to display all try at once, or if we should have to select the wipe.

This would allow comparing our own timers across all the wipes with what the top world is doing, and it would also highlight if we are a bit late on few mechanics or not.

The way I see it, is having the top tier list at the top, and a static div with our own logs at the bottom, so it would feel "integrated into the same view", but always displaying no matter to what we are comparing to.

What do you think about it?

**Comment by gitarrg** [comment]
Hey Seraf,

Yeah, I like this idea in general, however implementing something like this would be a potentially big step up in terms of resources needed _(worker to load the logs, api calls to warcraftlogs, cache/database storage)_
So while I'm happy to collect some ideas for this, I'm afraid this feature would have to wait for the next 1-2 major-updates of the page, as I'd prefer to first finish and stabilize all the current features.

that being said, I like how you suggest the display.  Personally I'd probl put the custom logs on top, but thats something I'd have to see how it looks and play around a bit.
In terms of wipes..  maybe letting the user select which pulls to display would be nice...
